sudo: required
language: python
services:
 - docker
before_install:
  - docker build -t secopsltd/brumairasa .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push secopsltd/brumairasa
install: true
